/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Patient {
  'age' : bigint,
  'sex' : string,
  'uid' : string,
  'contact' : string,
  'imageData' : string,
  'canvasData' : string,
  'name' : string,
  'historyNotes' : string,
  'doctorName' : string,
  'registrationDate' : string,
}
export interface _SERVICE {
  'deletePatient' : ActorMethod<[string], Patient>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getPatientByUid' : ActorMethod<[string], Patient>,
  'register' : ActorMethod<[Patient], undefined>,
  'updatePatient' : ActorMethod<[Patient], Patient>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];