/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'sex' : IDL.Text,
  'uid' : IDL.Text,
  'contact' : IDL.Text,
  'imageData' : IDL.Text,
  'canvasData' : IDL.Text,
  'name' : IDL.Text,
  'historyNotes' : IDL.Text,
  'doctorName' : IDL.Text,
  'registrationDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'deletePatient' : IDL.Func([IDL.Text], [Patient], []),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPatientByUid' : IDL.Func([IDL.Text], [Patient], ['query']),
  'register' : IDL.Func([Patient], [], []),
  'updatePatient' : IDL.Func([Patient], [Patient], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'sex' : IDL.Text,
    'uid' : IDL.Text,
    'contact' : IDL.Text,
    'imageData' : IDL.Text,
    'canvasData' : IDL.Text,
    'name' : IDL.Text,
    'historyNotes' : IDL.Text,
    'doctorName' : IDL.Text,
    'registrationDate' : IDL.Text,
  });
  
  return IDL.Service({
    'deletePatient' : IDL.Func([IDL.Text], [Patient], []),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPatientByUid' : IDL.Func([IDL.Text], [Patient], ['query']),
    'register' : IDL.Func([Patient], [], []),
    'updatePatient' : IDL.Func([Patient], [Patient], []),
  });
};

export const init = ({ IDL }) => { return []; };